### ISSUE TITLE
Missing version in packagist

### ISSUE THREAD

**Issue by angelk** [Sibyx/phpGPX#10]
https://packagist.org/packages/sibyx/phpgpx
have only 1.0-RC1 and dev-master
Composer can't install [rc-2](https://github.com/Sibyx/phpGPX/releases/tag/1.0-RC2)
```
    - The requested package sibyx/phpgpx 3 exists as sibyx/phpgpx[1.0-RC1, dev-master] but these are rejected by your constraint.

```

**Comment by Sibyx** [comment]
Hi! Thanks, for reporting. It's looks like that I have to create a new version and we have to skip RC-2 on the packagist, because there is an invalid composer.json file in the release.

**Comment by Sibyx** [comment]
Version 1.0-RC2 is skipped in packagist, RC3 is released just now and should be available in packagist soon.
