### ISSUE TITLE
Cumulative Elevation Gain Stat

### ISSUE THREAD

**Issue by Shaydu** [Sibyx/phpGPX#11]
Hi,

Is there a way to calculate the cumulative elevation gain as part of the stats? I believe this is a new feature which doesn't exist today.

Thanks,
Steve

**Comment by Sibyx** [comment]
Hi,
yop this is kinda a new feature. If you want, feel free to create a pull request (if you want let me know to avoid the situation where both of us will implement the same feature).

All best
