### ISSUE TITLE
typo that lead to error

### ISSUE THREAD

**Issue by kruvas** [Sibyx/phpGPX#14]
hello, i notice a typo in 
/Models/Extensions/TrackPointExtension.php
here

	/**
	 * Heart rate in beats per minute.
	 * @var float
	 */
	public $hearthRate; 

that supposed to be 

	public $heartRate;

because when i try to manually create TrackPointExtension by
new \phpGPX\Models\Extensions\TrackPointExtension;
and then save it, i get

Notice:  Undefined property: phpGPX\Models\Extensions\TrackPointExtension::$heartRate in ****\phpGPX\Parsers\Extensions\TrackPointExtensionParser.php on line 88

because code expect heartRate var, not heart**h**Rate.
also this typo create two vars in extenstion, one of it empty

      ["hearthRate"]=>      NULL
      ["heartRate"]=>      float(107)

fix it please

**Comment by Sibyx** [comment]
Hi! Thank you very much. I will try to fix it ASAP (propaply this weekend, maybe tomorrow).

**Comment by Sibyx** [comment]
Issue should be resolved.
