### ISSUE TITLE
Empty array on load route

### ISSUE THREAD

**Issue by mujieniwa** [Sibyx/phpGPX#20]
Hi,
I was successfully load an array of waypoints and tracks, but failed with routes gpx file with a simple codes. Array points of route is empty.

```
use phpGPX\phpGPX;
$gpx = new phpGPX();
$file = $gpx->load('gps_result.gpx');
print_r($file);
```

By the way, thank you for your great work.

Regards,
M

**Comment by Sibyx** [comment]
Hi,
thank you for reporting. I found a typo in the parsing of routes in the library. I will try to resolve it this week.

**Comment by Sibyx** [comment]
Resolved in [RC-4](https://github.com/Sibyx/phpGPX/releases/tag/1.0-RC4)
