### ISSUE TITLE
Problem with composer installation

### ISSUE THREAD

**Issue by IndiAsh** [Sibyx/phpGPX#23]
There is a problem while installing through composer.

$ composer require sibyx/phpgpx

  [InvalidArgumentException]
  Could not find package sibyx/phpgpx.

  Did you mean one of these?
      sibyx/phpgpx
      danmatthews/phpgpx

**Comment by Sibyx** [comment]
Hmm, this is pretty weird. For me, it's working just fine and I have never heard of this problem before. Can you please attach your `composer.json` file?

**Comment by IndiAsh** [comment]
[composer.zip](https://github.com/Sibyx/phpGPX/files/1663785/composer.zip)

I also created an empty folder and run from that directory the command composer require sibyx/phpgpx and the same result.

**Comment by Sibyx** [comment]
I have found a solution. Composer looks for stable dependencies by default. Currently, the phpGPX is marked as pre-release and I didn't release a stable release yet (I want to write all unit and integration tests before releasing the first stable version).

Although the package is marked as pre-release I already use it in production without any problems.

The solution for you is asking composer to check for RC versions like this:

```bash
composer require sibyx/phpgpx:@RC
```

**Comment by IndiAsh** [comment]
Thank you. Now is ok.
