### ISSUE TITLE
Parse of GPX file failse if lastpointTime is not prestent

### ISSUE THREAD

**Issue by roynijkamp** [Sibyx/phpGPX#26]
When you try to parse a GPX file with only a timestamp on the firstpoint there will be an error.

I fixed the issue in the file Models/Segment.php with a check for the var $lastPoint->time
I changed line 100 from:
`if (isset($firstPoint->time) && $firstPoint->time instanceof \DateTime) {`
TO
`if (isset($firstPoint->time) && isset($lastPoint->time) && $firstPoint->time instanceof \DateTime) {`

**Comment by Sibyx** [comment]
Hi @roynijkamp,
thank you very much for reporting the issue. Would you like to create a pull request? (Just to know if I can push the fix by myself.)

**Comment by roynijkamp** [comment]
@Sibyx i created a pull request! Thanks for you're response

**Comment by Sibyx** [comment]
Resolved with #27
