### ISSUE TITLE
minAltitude seems to be missing/null if any points do not have an elev tag

### ISSUE THREAD

**Issue by ramblerswebs** [Sibyx/phpGPX#31]
# When I process the attached file the minAltitude seems to be missing or null in the stats object

1. Library version 1.0-RC5
2. PHP version 7.0
3. Detailed problem description

After processing the attached file, where some of the track points do not have elevations defined, the minAltitude is then missing in the track->stats object.
The code should ignore points without elevations.

[Venachar.gpx.txt](https://github.com/Sibyx/phpGPX/files/1883584/Venachar.gpx.txt)

PS thanks for otherwise great code, very useful.

**Comment by Sibyx** [comment]
Unable to replicate issue on PHP 7.4 with phpGPX version 1.1.1 (probably already resolved with $IGNORE_ELEVATION_0)
