### ISSUE TITLE
Error when TrkSeg is empty

### ISSUE THREAD

**Issue by QmarXX** [Sibyx/phpGPX#33]
TrkSeg can be empty on GPX 1.1 and it causes a problem in your library in method \phpGPX\Models\Track::recalculateStats when I try calculate statistics.

I got a few files with empty <trkseg> on end of files when I using export option on Endomondo.

I wrote quick fix to check trkseg is not empty and use only segments that have points:
```php
$firstSegment = null;

foreach ($this->segments as $segment) {
    if (!empty($segment->points)) {
        if (is_null($firstSegment)) {
            $firstSegment = $segment;
        }

        $lastSegment = $segment;
    }
}

if (!isset($firstSegment) || !isset($lastSegment)) {
    return;
}

$firstPoint = $firstSegment->points[0];
$lastPoint = end($lastSegment->points);
```

but maybe you will find more optimal solution.

**Comment by Sibyx** [comment]
Resolved in #40
