### ISSUE TITLE
Distance calculator - add altitude in formulas

### ISSUE THREAD

**Issue by Warxcell** [Sibyx/phpGPX#37]
Hello, right now distance calculator does not add altitude difference between points to distance, and when it's calculating route with elevation gain or loss the results are slightly not correct.

I used pythagorean to include altitude to distance. I don't know if this is correct, but results looks more or less correct. :)

```
  public function distanceLatLngAlt(float $lat1, float $lng1, float $alt1, float $lat2, float $lng2, float $alt2)
    {
        $distance = $this->distanceLatLng($lat1, $lng1, $lat2, $lng2);

        $elevDiff = abs($alt1 - $alt2);

        return sqrt(pow($distance, 2) + pow($elevDiff, 2));
    }
```
This formula is tested against 141 km path. The difference between distance with 2 formulas is almost 1km.

What do you think if we integrate this or some other formulas to include altitude in distance calculations?

**Comment by Sibyx** [comment]
Hi, nice idea. I am thinking of the implementation. If it's better to create a new attribute or create a configuration flag. What do you think? 

Sorry for the later response, I was on holiday.

**Comment by Warxcell** [comment]
I would probably refactor DistanceCalculator and instance of it instead static method.
Something like that:

```
$calculator = new DistanceCalculator($points);
$rawDistance = $calculator->getRawDistance();
$distanceWithAltitude = $calculator->getRealDistance()
```

Better ideas for method names?

**Comment by Sibyx** [comment]
Hmm, sounds good to me. I am just not sure about changing API (I am not proud about the library versioning :D )

**Comment by Warxcell** [comment]
Well, isn't that DistanceCalculator for internal use only? If so, shouldn't be a problem.

**Comment by Sibyx** [comment]
Ahh I see, sorry. So then is not problem at all ;)

**Comment by Sibyx** [comment]
Implemented as `realDistance` property in `Route`, `Segment`, `Stats`, `Track` objects.
