### ISSUE TITLE
Error when last trk point does not have a time set

### ISSUE THREAD

**Issue by ramblerswebs** [Sibyx/phpGPX#38]
Using RC5

I the first point of a track has a time but that last point does not then the code in Segment.php fails at line 101

```
if (isset($firstPoint->time) && $firstPoint->time instanceof \DateTime) {
			$this->stats->duration = $lastPoint->time->getTimestamp() - $firstPoint->time->getTimestamp();

			if ($this->stats->duration != 0) {
				$this->stats->averageSpeed = $this->stats->distance / $this->stats->duration;
			}

			if ($this->stats->distance != 0) {
				$this->stats->averagePace = $this->stats->duration / ($this->stats->distance / 1000);
			}
		}

```
A check is needed to see if $lastpoint->time is set or not.

PS great package - good work

test file
[Cedar-Mawdesley-Moss-4ml.gpx.txt](https://github.com/Sibyx/phpGPX/files/2628544/Cedar-Mawdesley-Moss-4ml.gpx.txt)

**Comment by Sibyx** [comment]
From #27 library is not crashing, but startedAt and finishedAt is filled only if timestamp was present in the first (or last) segment record. This behaviour will be changed in 2.x  and startedAt will have value of the first timestamp in the segment and finishedAt will have value of the last timestamp present in the segment.
