### ISSUE TITLE
use custom trackpoint extension (in this case: Bad-Elf)?

### ISSUE THREAD

**Issue by wivaku** [Sibyx/phpGPX#42]
Not an issue, but a question really.

Can I add/use custom trackpoint extensions?

This so I can read this Bad Elf speed extension:
```
<trkpt lat="54.315933" lon="-130.325592">
  <ele>49.7</ele>
  <time>2013-06-18T17:02:04Z</time>
  <hdop>1.4</hdop>
  <extensions>
    <badelf:speed>2.006332</badelf:speed>
  </extensions>
</trkpt>
```

They also have metadata extensions, but I am less interested in those.
```
        <metadata>
                <extensions>
                        <!-- Name -->
                        <badelf:modelName>Bad Elf GPS Pro</badelf:modelName>
                        <!-- Ser No -->
                        <badelf:modelSerialNumber>118887</badelf:modelSerialNumber>
                        <!-- Model -->
                        <badelf:modelNumber>BE-GPS-2200</badelf:modelNumber>
                        <!-- Hardware Revision -->
                        <badelf:modelHardwareRevision>2.0.0</badelf:modelHardwareRevision>
                        <!-- Firmware Revision -->
                        <badelf:modelFirmwareRevision>2.0.48</badelf:modelFirmwareRevision>
                </extensions>
        </metadata>
```

Namespace:
```
<gpx xmlns="http://www.topografix.com/GPX/1/1"
                xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3"
                xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1"
                xmlns:badelf="http://bad-elf.com/xmlschemas"
                version="1.1"
                creator="Bad Elf GPS Pro 2.0.48"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www.garmin.com/xmlschemas/GpxExtensionsv3.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v1 http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd http://bad-elf.com/xmlschemas http://bad-elf.com/xmlschemas/GpxExtensionsV1.xsd">
```

**Comment by Sibyx** [comment]
Hi @wivaku,
right now there is no implementation for Bad-Elf trackpoint extension. You need to write your own:

- parser (check existing [TrackPointExtensionParser](https://github.com/Sibyx/phpGPX/blob/master/src/phpGPX/Parsers/Extensions/TrackPointExtensionParser.php))
- model ([TrackPointExtension model](https://github.com/Sibyx/phpGPX/blob/master/src/phpGPX/Models/Extensions/TrackPointExtension.php))

Then you need to add your parser into [ExtensionParser](https://github.com/Sibyx/phpGPX/blob/master/src/phpGPX/Parsers/ExtensionParser.php).

I hope I answered your question, if there is something I can help you feel free to ask. If you are going to have a PR, I will gladly merge it :) And happy new year! 🥳

**Comment by wivaku** [comment]
Thanks for the quick reply (and: happy new year to you as well!)
Writing my own is probably beyond my current skillset. I.e. not sure how to add a 2nd one.

Related / as an alternative: when parsing, would it be possible to group all unsupported extensions under "unsupported"?

e.g. Bad Elf:
```
  +extensions: phpGPX\Models\Extensions^ {#783
    +trackPointExtension: null
    +unsupported: [
      "speed": 2.006332
    ]
  }
```
compared:
Garmin:
```
  +extensions: phpGPX\Models\Extensions^ {#780
    +trackPointExtension: phpGPX\Models\Extensions\TrackPointExtension^ {#786
      +aTemp: 19.5
      +avgTemperature: 19.5
      +wTemp: null
      +depth: null
      +heartRate: null
      +hr: null
      +cadence: null
      +cad: null
      +speed: null
      +course: null
      +bearing: null
      +namespace: "http://www.garmin.com/xmlschemas/TrackPointExtension/v2"
      +extensionName: "TrackPointExtension"
    }
    +unsupported: [] 
```

**Comment by Sibyx** [comment]
The library already suppose to work like you described (unsupported should appear in `unsupported` field). I am not sure if it works properly (there is a nasty two years old [FIXME comment](https://github.com/Sibyx/phpGPX/blob/master/src/phpGPX/Parsers/ExtensionParser.php#L43) - I am sorry). Anyway, I should check it out

**Comment by wivaku** [comment]
That is hopeful! Will monitor this ticket. No hurry.
The above shows the details of the Bad Elf example, if you need a complete example file: let me know.

**Comment by Sibyx** [comment]
If you can share a GPX file, testing will be much more easier!

**Comment by wivaku** [comment]
Done, sent to your gmail address.

**Comment by Sibyx** [comment]
Hi,
In last [commit](https://github.com/Sibyx/phpGPX/commit/13d5ae5900909e4c2ef042d3390539f621cf0ba3) I have fixed ExtensionParser to correctly fill unsupported extension field.

There is no new release, so you have to use master branch.

**Comment by wivaku** [comment]
Thanks a lot! I can confirm this works. Used `composer require sibyx/phpgpx:dev-master`.
