### ISSUE TITLE
Elevation string float becomes null in getJSON() call

### ISSUE THREAD

**Issue by sandcore-dev** [Sibyx/phpGPX#43]
Hi,

I was testing phpGPX with points from a database that contained timestamp, latitude, longitude and elevation and noticed that the JSON output had "null" in the elevation property. This is because the elevation was a string.

Remarkably enough, this problem did not occur when exporting to XML.

1. Package version: 1.0-RC5, also tested on dev-master
2. PHP version: 7.4.1

## Expected behaviour

Silently cast the value to a float or null.

## Possible solution

`SerializationHelper::floatOrNull()` should use `is_numeric()` instead of `is_float() || is_integer()`

## Alternate solution

You could also throw an exception if the value is neither a float nor null. Maybe a 'strict mode' could be offered for people who prefer to get an exception.

**Comment by Sibyx** [comment]
Hello, thank you for reporting issue. Would you like to offer a PR? Or I can check it out in next few days.

**Comment by sandcore-dev** [comment]
Pull request #44 submitted. Not just about floatOrNull though.

**Comment by Sibyx** [comment]
Looks good, thank you very much!
