### ISSUE TITLE
cumulativeElevationLoss is missing in stats

### ISSUE THREAD

**Issue by jesuspicornell** [Sibyx/phpGPX#46]
# Problem description

1. v1,0RC5
2. PHP 7
3. cumulative elevation loss is missing in stats.

For example, when I calculate the stats of a GPX file, I get this answer:

[{"description":"Osterrunde um Bergen-Vogtland.gpx","distance":20843.2107222357080900110304355621337890625,"avgSpeed":0.98572762933249979955263597730663605034351348876953125,"avgPace":1014.4790206166434245460550300776958465576171875,"minAltitude":444.1000000000000227373675443232059478759765625,"maxAltitude":601,"cumulativeElevationGain":370.7000000000001591615728102624416351318359375,"startedAt":"2020-04-12T00:41:05+00:00","finishedAt":"2020-04-12T06:33:30+00:00","duration":21145}]'

It is also missing in this document: https://github.com/Sibyx/phpGPX/blob/69846b781000c12c15eea26c2808fe67f0305802/docs/phpGPX-Models-Stats.md

# Expected behaviour

[{"description":"Osterrunde um Bergen-Vogtland.gpx","distance":20843.2107222357080900110304355621337890625,"avgSpeed":0.98572762933249979955263597730663605034351348876953125,"avgPace":1014.4790206166434245460550300776958465576171875,"minAltitude":444.1000000000000227373675443232059478759765625,"maxAltitude":601,"cumulativeElevationGain":370.7000000000001591615728102624416351318359375,"**cumulativeElevationLoss":370.7000000000001591615728102624416351318359375,**"startedAt":"2020-04-12T00:41:05+00:00","finishedAt":"2020-04-12T06:33:30+00:00","duration":21145}]'

# Possible solution

A possible solution if you have any.

# Something interesting or funny

Joke or interesting fact to made readers better day :) For example: Ants get drunk and act silly, causing their friend-ants to throw them in puddles of water.

# Checklist

Put `x` into brackets if true.

[x ] PHP version I use
[ x] Package version I use

**Comment by lukey78** [comment]
Actually, this was contributed by me over 2 years ago. Why don't close this one?
