### ISSUE TITLE
GeoJSON support

### ISSUE THREAD

**Issue by Sibyx** [Sibyx/phpGPX#5]
Add ability to read/write [GeoJSON](http://geojson.org) data files.

GeoJSON is a format for encoding a variety of geographic data structures.

**Comment by tomsb** [comment]
Currently implemented GeoJSON format is not valid. Validator: https://geojsonlint.com/

**Comment by Sibyx** [comment]
Hello @tomsb, currently there is no geojson implementation. Ticket is closed because I decided to postpone works on that. The json output has same structure as a gpx object (my bad for wrong/missing docs). 

I would like to implement such feature after 2.x release which will be core migration to PHP 8.

Sorry for misconvenience
