### ISSUE TITLE
Error installing with composer

### ISSUE THREAD

**Issue by richardpbull** [Sibyx/phpGPX#53]
composer require sibyx/phpgpx:@1.1.2

                                                                              
  [UnexpectedValueException]                                                  
  Could not parse version constraint @1.1.2: Invalid version string "@1.1.2"

![image](https://user-images.githubusercontent.com/5243046/122004042-98869780-cd4f-11eb-92f3-d7386c840255.png)

**Comment by Sibyx** [comment]
Hello @richardpbull,
there is a typo in README file, if you want to install package via composre you should use: `composer require sibyx/phpgpx:1.1.2`. Thank you for noticing.

**Comment by richardpbull** [comment]
thank you - using composer require sibyx/phpgpx worked fine too. 
Beautiful piece of coding which gives accurate results (of course) and saves a lot of time. Thank you!
