### ISSUE TITLE
Class Error (Fatal error: Uncaught Error: Class "phpGPX\phpGPX" not found in)

### ISSUE THREAD

**Issue by Stef-Schalks** [Sibyx/phpGPX#60]
# Problem Description:

Error:
`Fatal error: Uncaught Error: Class "phpGPX\phpGPX" not found in "C://MYFILEPATH"`

I use *phpGPX* version *1.1.3* & *PHP* version *8.0.14*

I installed *phpGPX* with composer with the command:
`composer require sibyx/phpgpx:1.1.3`

My code:
```php
<?php
use phpGPX\phpGPX;

$gpx = new phpGPX();
	
$file = $gpx->load('example.gpx');
	
foreach ($file->tracks as $track)
{
    // Statistics for whole track
    $track->stats->toArray();
    
    foreach ($track->segments as $segment)
    {
    	// Statistics for segment of track
    	$segment->stats->toArray();
    }
}
?>
```

Someone know this?

Kind Regards,
Stef

@Sibyx

**Comment by Sibyx** [comment]
Hello @Stef-Schalks,

just to be sure, do you have somewhere included composer autoload?

```
require_once(vendor/autoload.php');
```

**Comment by Stef-Schalks** [comment]
Hey @Sibyx, thank you for your quick respond

The example said I should use "use":
`use phpGPX\phpGPX;`

But I'll try the autoload!

**Comment by Stef-Schalks** [comment]
Okay thanks for the time and effort! It works now! Issue closed!
