### ISSUE TITLE
[PR advise] Add coordinates for remarqued statistic points

### ISSUE THREAD

**Issue by nono303** [Sibyx/phpGPX#63]
Hi @sibyx,
Many Thx for this great package!
I'm working on a [PR](https://github.com/nono303/phpGPX/commit/2abb6356021e04f46260ac92c952c83fd828d814) to add coordinates for remarked statistic points (start, end, minAlt, maxAlt) , to facilitates wpt generation of them.
Which output would you prefer? (example with minAltitude):
1) Nice but breaking
```php
Array (
    [minAltitude] => Array
        (
            [ele] => 1518
            [lat] => 45.6139274
            [lng] => 7.3420498
        ),
    ...
    )
```
2) ...not breaking
```php
Array (
    [minAltitude] => 1518
    [minAltitudeCoords] => Array
        (
            [lat] => 45.6139274
            [lng] => 7.3420498
        ),
    ...
    )
```
3)  all added coords in a single Statistics key
```php
Array (
    [coords] => Array (
        [minAltitude] => Array (
                [lat] => 45.6139274
                [lng] => 7.3420498
            ),
        [maxAltitude] => Array (
                [lat] => 45.5916625
                [lng] => 7.278847
            )
        ),
	...
    )
```

**Comment by Sibyx** [comment]
Hello @nono303, thank you for preparing a PR. I think it's more appropriate to go with non-breaking option. I hope I will prepare 2.x release with PHP 8.x support so there will be a place for breaking changes.

**Comment by nono303** [comment]
Thx @Sibyx!
will implement it with option **2**
