### ISSUE TITLE
Split loading and parsing in separate methods

### ISSUE THREAD

**Issue by lommes** [Sibyx/phpGPX#8]
Hi, 

I played around and really like your package. It would be a nice addition if loading and parsing of the gpx data would be split in different methods, so it can be parsed from database entries.

Regards
Timo

**Comment by Sibyx** [comment]
Hi,
thanks! So if I get it right you want to split phpGPX::load() method into multiple methods which allows loading from other sources? For example:

- loadFromFile()
- loadFromString()

Regards
Jakub

**Comment by lommes** [comment]
Or, which might even be easier, keep the load method with the file as parameter, read files content and directly pass it to a second method which does the stuff from [here](https://github.com/Sibyx/phpGPX/blob/master/src/phpGPX/phpGPX.php#L63) to [here](https://github.com/Sibyx/phpGPX/blob/master/src/phpGPX/phpGPX.php#L80). So load will stay the loadFromFile and the new method can be used directly to load from string.

**Comment by Sibyx** [comment]
Yop, also quite a good idea, but there is one more thing to resolve: we have to somehow provide a backward compatibility with previous. I am not very sure if its a good idea to change a parameter in the [phpGPX::load](https://github.com/Sibyx/phpGPX/blob/master/src/phpGPX/phpGPX.php#L60) function.

**Comment by lommes** [comment]
This will not break anything since the path is already the only parameter. I will create a pull request to clarify later.

**Comment by Sibyx** [comment]
Ah, yes I see, we just need implement extra function for loading data from string which will be used in phpGPX::load(). I hope I get it now :D Looking forward to your pull request!

**Comment by Sibyx** [comment]
Resolved & implemented with #9 Thank you 👍
